// A real fixed list, not free text -- prevents typos/inconsistent spelling
// ("Rottweiler" vs "Rotweiler") the same way species and size already are.
// Scoped to dogs only.

export const DOG_BREEDS = [
  "Mixed breed",
  "Labrador Retriever",
  "Golden Retriever",
  "German Shepherd",
  "Boerboel",
  "Jack Russell Terrier",
  "Staffordshire Bull Terrier",
  "American Staffordshire Terrier (Pitbull type)",
  "Beagle",
  "Border Collie",
  "Rottweiler",
  "Dachshund",
  "French Bulldog",
  "English Bulldog",
  "Poodle (Standard)",
  "Poodle (Miniature)",
  "Poodle (Toy)",
  "Chihuahua",
  "Pug",
  "Boxer",
  "Doberman Pinscher",
  "Great Dane",
  "Rhodesian Ridgeback",
  "Cavalier King Charles Spaniel",
  "Shih Tzu",
  "Yorkshire Terrier",
  "Maltese",
  "Miniature Schnauzer",
  "Cocker Spaniel",
  "Springer Spaniel",
  "Husky (Siberian)",
  "Alaskan Malamute",
  "Australian Shepherd",
  "Australian Cattle Dog",
  "Bull Terrier",
  "Bullmastiff",
  "Weimaraner",
  "Vizsla",
  "Pointer",
  "Basset Hound",
  "Bloodhound",
  "Whippet",
  "Greyhound",
  "Italian Greyhound",
  "Papillon",
  "Pomeranian",
  "Bichon Frise",
  "Havanese",
  "Shiba Inu",
  "Akita",
  "Chow Chow",
  "Basenji",
  "Africanis",
  "Anatolian Shepherd",
  "Belgian Malinois",
  "Bernese Mountain Dog",
  "Cane Corso",
  "Newfoundland",
  "St. Bernard",
  "Old English Sheepdog",
  "Corgi (Pembroke Welsh)",
  "Corgi (Cardigan Welsh)",
  "Dalmatian",
  "Schnauzer (Standard)",
  "Schnauzer (Giant)",
  "West Highland White Terrier",
  "Scottish Terrier",
  "Cairn Terrier",
  "Miniature Pinscher",
  "Lhasa Apso",
  "Shar Pei",
  "Boston Terrier",
  "Brittany",
  "German Shorthaired Pointer",
  "Other / not listed",
] as const;
